import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css';
import { cn } from '@/lib/utils';
import { Providers } from '@/components/Providers'
import Navbar from '@/components/Navbar';
import { Toaster } from 'react-hot-toast';



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cn('bg-white text-slate-900 antialiased', inter.className)}>
      <body className='min-h-screen bg-slate-50 dark:bg-slate-900 antialiased'>
        <Providers>
        {children}
        <Toaster position='bottom-right' />
        <Navbar />
        </Providers>
        {/* Allow for height on mobile devices */}
        <div className='h-40 md:hidden'></div>
        </body>
    </html>
  )
}
